/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transaksi.penjualan;

/**
 *
 * @author TAUFIQ
 */
public class Program_Transaksi_Penjualan extends javax.swing.JFrame {

    /**
     * Creates new form Program_Transaksi_Penjualan
     */
    public Program_Transaksi_Penjualan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbkodekonsumen = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtketerangan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbkodebarang = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtnamabarang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txthargabarang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtsatuan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtjumlahbeli = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtdiskon = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txttotalharga = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtuangpembayaran = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtuangkembalian = new javax.swing.JTextField();
        btnprosesdiskon = new javax.swing.JButton();
        btnprosestotal = new javax.swing.JButton();
        btnuangpembayaran = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel1.setText("Transaksi Penjualan Toko 16");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("Nama Konsumen :");

        txtnama.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setText("Kode Konsumen :");

        cmbkodekonsumen.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cmbkodekonsumen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KS0001", "KS0002" }));
        cmbkodekonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkodekonsumenActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setText("Keterangan :");

        txtketerangan.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtketerangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtketeranganActionPerformed(evt);
            }
        });
        txtketerangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtketeranganKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setText("Kode Barang :");

        cmbkodebarang.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cmbkodebarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BM001", "BM002", "BM003", "BM004", "BM005" }));
        cmbkodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkodebarangActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setText("Nama Barang :");

        txtnamabarang.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel7.setText("Harga Barang :");

        txthargabarang.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txthargabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargabarangActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setText("Satuan :");

        txtsatuan.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel9.setText("Jumlah Beli :");

        txtjumlahbeli.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtjumlahbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahbeliActionPerformed(evt);
            }
        });
        txtjumlahbeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtjumlahbeliKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel10.setText("Diskon :");

        txtdiskon.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel11.setText("Total Harga :");

        txttotalharga.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel12.setText("Uang Pembayaran :");

        txtuangpembayaran.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel13.setText("Uang Kembalian :");

        txtuangkembalian.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        btnprosesdiskon.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnprosesdiskon.setText("Proses Diskon");
        btnprosesdiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesdiskonActionPerformed(evt);
            }
        });

        btnprosestotal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnprosestotal.setText("Proses Total");
        btnprosestotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosestotalActionPerformed(evt);
            }
        });

        btnuangpembayaran.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnuangpembayaran.setText("Proses Uang Pembayaran");
        btnuangpembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuangpembayaranActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnexit.setText("X");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txthargabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtjumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txttotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtuangpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnhapus)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbkodekonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnprosestotal)
                            .addComponent(btnprosesdiskon)
                            .addComponent(btnuangpembayaran))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtuangkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(224, 224, 224)
                .addComponent(btnexit)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnexit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cmbkodekonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txthargabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtjumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprosesdiskon))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(btnprosestotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuangpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(btnuangpembayaran))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtuangkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbkodekonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkodekonsumenActionPerformed
        // TODO add your handling code here:
        String kodeks, keterangan ;
        
        kodeks = String.valueOf(cmbkodekonsumen.getSelectedItem());
        
        switch (kodeks) {
            case "KS0001":
                keterangan = "Member";
                break;
            case "KS0002":
                keterangan = "Konsumen Biasa";
                break;
            default:
                keterangan = "Tidak Terdaftar";
                break;
        }
        txtketerangan.setText(""+keterangan);
    }//GEN-LAST:event_cmbkodekonsumenActionPerformed

    private void cmbkodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkodebarangActionPerformed
        // TODO add your handling code here:
        String kdbarang,namabarang = null,satuan = null;
        double hargabarang = 0;
        
        kdbarang =  String.valueOf(cmbkodebarang.getSelectedItem());
        
        switch (kdbarang) {
            case "BM001":
                namabarang = "Swallow";
                hargabarang = 13000;
                satuan = "pasang";
                break;
            case "BM002":
                namabarang = "Buku Tulis";
                hargabarang = 20000;
                satuan = "lusin";
                break;
            case "BM003":
                namabarang = "Pensil";
                hargabarang = 3000;
                satuan = "pcs";
                break;
            case "BM004":
                namabarang = "Bolpoint";
                hargabarang = 12000;
                satuan = "pack";
                break;
            case "BM005":
                namabarang = "Penghapus";
                hargabarang = 5000;
                satuan = "pcs";
                break;
            default:
                break;
        }
        txtnamabarang.setText("" + namabarang);
        txthargabarang.setText("" + hargabarang);
        txtsatuan.setText("" + satuan);
    }//GEN-LAST:event_cmbkodebarangActionPerformed

    private void txtjumlahbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahbeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahbeliActionPerformed

    private void btnprosesdiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesdiskonActionPerformed
        // TODO add your handling code here:
        double hargabarang, diskon;
        int jumlahbeli;
        
        jumlahbeli = Integer.parseInt(txtjumlahbeli.getText());
        hargabarang = Double.parseDouble(txthargabarang.getText());
        
        if (jumlahbeli > 10) {
           diskon = hargabarang * 0.2;
        }else
        {
            diskon = 0;
        }
        txtdiskon.setText("" + diskon);
    }//GEN-LAST:event_btnprosesdiskonActionPerformed

    private void btnprosestotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosestotalActionPerformed
        // TODO add your handling code here:
        double hargabarang, diskon, totalbayar;
        int jumlahbeli;
        
        hargabarang = Double.parseDouble(txthargabarang.getText());
        jumlahbeli = Integer.parseInt(txtjumlahbeli.getText());
        diskon = Double.parseDouble(txtdiskon.getText());
        
        totalbayar = (hargabarang * jumlahbeli)-diskon;
        txttotalharga.setText("" + totalbayar);
    }//GEN-LAST:event_btnprosestotalActionPerformed

    private void btnuangpembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuangpembayaranActionPerformed
        // TODO add your handling code here:
        double totalbayar,uangpembayaran,uangkembalian;
        
        totalbayar = Double.parseDouble(txttotalharga.getText());
        uangpembayaran = Double.parseDouble(txtuangpembayaran.getText());
        
        if (uangpembayaran > totalbayar){
            uangkembalian = uangpembayaran - totalbayar;
            txtuangkembalian.setText("" + uangkembalian);
        }else
            txtuangkembalian.setText("Uang Anda Kurang");
    }//GEN-LAST:event_btnuangpembayaranActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        txtnama.setText("");
        txtketerangan.setText("");
        txtnamabarang.setText("");
        txthargabarang.setText("");
        txtsatuan.setText("");
        txtjumlahbeli.setText("");
        txtdiskon.setText("");
        txttotalharga.setText("");
        txtuangpembayaran.setText("");
        txtuangkembalian.setText("");
          cmbkodekonsumen.setSelectedItem(null);
          cmbkodebarang.setSelectedItem(null);
          txtnama.requestFocus();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void txthargabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargabarangActionPerformed

    private void txtjumlahbeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahbeliKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar();
        if (!(Character.isDigit(enter)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtjumlahbeliKeyTyped

    private void txtketeranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtketeranganActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_txtketeranganActionPerformed

    private void txtketeranganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtketeranganKeyTyped
        // TODO add your handling code here:
         char enter=evt.getKeyChar();
        if (!(Character.isDigit(enter)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtketeranganKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program_Transaksi_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Program_Transaksi_Penjualan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnprosesdiskon;
    private javax.swing.JButton btnprosestotal;
    private javax.swing.JButton btnuangpembayaran;
    private javax.swing.JComboBox<String> cmbkodebarang;
    private javax.swing.JComboBox<String> cmbkodekonsumen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtdiskon;
    private javax.swing.JTextField txthargabarang;
    private javax.swing.JTextField txtjumlahbeli;
    private javax.swing.JTextField txtketerangan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField txtsatuan;
    private javax.swing.JTextField txttotalharga;
    private javax.swing.JTextField txtuangkembalian;
    private javax.swing.JTextField txtuangpembayaran;
    // End of variables declaration//GEN-END:variables
}
